backend:
  name: github
  branch: main
  repo: SebastianOpperman/mythicshop
media_folder: "public/admin/uploads"
collections:
  - label: "Content"
    name: "content"
    folder: "public/content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
